[package]
name = "conclave-client"
build = "build.rs"
description = "Client application for the Conclave communications environment"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
# Internal
conclave-common = { workspace = true }

# External
anyhow = { workspace = true, features = ["std"] }
arboard = { workspace = true, features = ["image-data", "wayland-data-control"] }
base64 = { workspace = true, features = ["alloc"] }
clap = { workspace = true, features = ["color", "derive", "help", "std", "string", "suggestions"] }
chrono = { workspace = true, features = ["clock", "serde", "std"] }
dashmap = { workspace = true, features = ["inline"] }
domain = { workspace = true, features = ["resolv"] }
eframe = { workspace = true, features = ["accesskit", "default_fonts", "serde", "wayland", "wgpu", "x11"] }
hex = { workspace = true, features = ["alloc"] }
image = { workspace = true, features = ["jpeg", "png"] }
mdns-sd = { workspace = true }
rfd = { workspace = true, features = ["xdg-portal", "wayland"] }
semver = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
toml = { workspace = true, features = ["default", "parse"] }
tracing = { workspace = true, features = ["attributes", "max_level_info", "std"] }
wgpu = { workspace = true, features = ["std"] }
zeroize = { workspace = true, features = ["aarch64", "derive", "serde"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
wgpu = { workspace = true, features = ["vulkan"], optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { workspace = true, features = ["metal"] }

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { workspace = true, features = ["dx12"] }

[build-dependencies]
chrono = { workspace = true, features = ["now"] }
