[package]
name = "conclave-tracker"
build = "build.rs"
description = "Tracker for the Conclave communications environment, so clients may find servers"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
gui = ["dep:eframe"]

[dependencies]
# Internal
conclave-common = { workspace = true }

# External
anyhow = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["color", "derive", "help", "std", "string", "suggestions"] }
dashmap = { workspace = true, features = ["inline"] }
eframe = { workspace = true, features = ["accesskit", "default_fonts", "glow"], optional = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync"] }
toml = { workspace = true, features = ["display", "parse", "serde"] }
tracing = { workspace = true, features = ["attributes", "std"] }

[dev-dependencies]
tempdir = { workspace = true }

[build-dependencies]
chrono = { workspace = true, features = ["now"] }
winresource = { workspace = true, features = ["toml"] }

[package.metadata.deb]
assets = [
    ["target/release/conclave-tracker", "usr/sbin/conclave-tracker", "755"],
    ["tracker.toml", "etc/conclave/tracker.toml", "600"],
    ["README.md", "usr/share/doc/conclave-tracker/README", "644"],
]
changelog = "debian/changelog"
conf-files = ["/etc/conclave/tracker.toml"]
copyright = "2026, Conclave Developers"
depends = "$auto"
extended-description = ""
maintainer-scripts = "debian/scripts"
priority = "optional"
section = "network"
systemd-units = { enable = false }

[package.metadata.winresource]
OriginalFilename = "CONCLAVE-TRACKER.EXE"
LegalCopyright = "Copyright © 2026, Conclave Developers"