#!/bin/sh

set -e

# Postinstall script for Conclave Tracker, based on Postgres' script.

# Add the user if it doesn't exist.
if ! getent passwd ccsd > /dev/null; then
    adduser --system --home /var/lib/conclave --no-create-home \
        --shell /bin/bash --group --gecos "Conclave Services" ccsd
fi

# if the user was created manually, make sure the group is there as well
if ! getent group ccsd > /dev/null; then
    addgroup --system ccsd
fi
# make sure ccsd is in the ccsd group
if ! id -Gn ccsd | grep -qw ccsd; then
    adduser ccsd ccsd
fi

# Generate the default config and empty database
/usr/sbin/conclave-server run -d /etc/conclave/server.db -c /etc/conclave/server.toml --gen-config

chown ccsd:ccsd /etc/conclave
chmod 0770 /etc/conclave
chmod 0600 /etc/conclave/server.db /etc/conclave/server.toml
chown ccsd:ccsd /etc/conclave/server.db /etc/conclave/server.toml

#DEBHELPER#
