[package]
name = "conclave-server"
build = "build.rs"
description = "Server application and library for the Conclave communications environment"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
gui = ["dep:eframe", "dep:wgpu", "dep:tracing-subscriber"]

[dependencies]
# Internal
conclave-common = { workspace = true }

# External
anyhow = { workspace = true, features = ["std"] }
argon2 = { workspace = true, features = ["alloc", "getrandom", "password-hash", "zeroize"] }
async-sqlite = { workspace = true, features = ["bundled", "chrono", "fallible_uint"] }
base64 = { workspace = true, features = ["alloc"] }
chrono = { workspace = true, features = ["clock", "std"] }
clap = { workspace = true, features = ["color", "derive", "help", "std", "string", "suggestions"] }
dialoguer = { workspace = true, features = ["password"] }
ed25519-dalek = { workspace = true, features = ["serde"] }
eframe = { workspace = true, features = ["accesskit", "default_fonts", "wayland", "wgpu", "x11"], optional = true }
futures = { workspace = true, features = ["executor"] }
hex = { workspace = true, features = ["alloc", "std"] }
mdns-sd = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["alloc", "std"] }
sysinfo = { workspace = true, features = ["disk"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
toml = { workspace = true, features = ["parse", "display", "serde"] }
tracing = { workspace = true, features = ["attributes", "max_level_info", "std"] }
tracing-subscriber = { workspace = true, features = ["fmt", "registry", "std"], optional = true }
uuid = { workspace = true, features = ["v4"] }
wgpu = { workspace = true, features = ["std"], optional = true }
zeroize = { workspace = true, features = ["aarch64", "alloc", "std"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
wgpu = { workspace = true, features = ["vulkan"], optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { workspace = true, features = ["metal"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { workspace = true, features = ["dx12"], optional = true }

[build-dependencies]
chrono = { workspace = true, features = ["now"] }

[dev-dependencies]
conclave-tracker = { workspace = true }
tempdir = { workspace = true }

[package.metadata.deb]
assets = [
    ["target/release/conclave-server", "usr/sbin/conclave-server", "755"],
    ["README.md", "usr/share/doc/conclave-server/README", "644"],
]
changelog = "debian/changelog"
copyright = "2026, Conclave Developers"
depends = "$auto"
extended-description = ""
maintainer-scripts = "debian/scripts"
priority = "optional"
section = "network"
systemd-units = { enable = false }
